version: "3.8"
services:

  app:
    build: "."
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - "postgres"
      - "nats-streaming"
      - "migrate"
  
  nats-streaming:
    image: nats-streaming:latest
    ports:
     - "4222:4222"
     - "8222:8222"

  postgres:
    image:
      postgres:16.2-alpine
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  migrate:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://${DBUSER}:${DBPASSWORD}@${DBHOST}/${DATABASE}?sslmode=${DBSSLMODE}", "up" ]
    depends_on:
      - "postgres"
    restart: on-failure